#! /usr/bin/env bash

#- Sparse runoff (pkg/rnf) version of input.icedyn: the same set-up,
#  with the dense runoffFile replaced by the sparse runoff_sparse_const.nc
#  of this directory. Everything else comes from ../input.icedyn, except
#  data.pkg (which adds useRNF) and data.exf (which blanks runoffFile),
#  which this directory holds.

#- in order to save disc space, take grid files
#- from this dir:
fromDir="../../tutorial_held_suarez_cs/input"

fileList=`( cd $fromDir ; ls grid_cs32.face00?.bin )`

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

#- take the set-up of input.icedyn (data, pickups, forcing, tr_checklist)
#  from this dir. The links are forced: the test harness has already
#  linked the files of input/ for every name this directory does not
#  hold, and the input.icedyn version is the one this case runs.
fromDir="../input.icedyn"
skipList="data.pkg data.exf prepare_run"

fileList=`( cd $fromDir ; ls )`

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    skip=0
    for yy in $skipList
    do
      if test "x$xx" = "x$yy" ; then skip=1 ; fi
    done
    if test $skip = 0 -a -r ${fromDir}/$xx ; then
      lnkList=${lnkList}" "$xx
      ln -sf ${fromDir}/$xx .
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
